export const CHOCOLATES_ACTION_TYPES = {
    FETCH_CHOCOLATES_START: 'chocolate/FETCH_CHOCOLATES_START',
    FETCH_CHOCOLATES_SUCCESS: 'chocolate/FETCH_CHOCOLATES_SUCCESS',
    FETCH_CHOCOLATES_FAILED: 'chocolate/FETCH_CHOCOLATES_FAILED'
};