export const CANDYS_ACTION_TYPES = {
    FETCH_CANDYS_START: 'candy/FETCH_CANDYS_START',
    FETCH_CANDYS_SUCCESS: 'candy/FETCH_CANDYS_SUCCESS',
    FETCH_CANDYS_FAILED: 'candy/FETCH_CANDYS_FAILED'
};